### PR TITLE
Fix hidden discovered letters in Hangman JavaScript version, #53

### PR DESCRIPTION
**Pull request by exiam**
Fixes following issue (#53) for JavaScript version:

> A letter which is being shown the first time may be hidden in a word. So we have to check this letter even if it is already shown at the beginning of the game

The fix might be the same for the Python version but I wasn't able to test it on my environment.

### CODE REVIEW

**Comment by Seniru** [comment]
Thanks for spending your time to contribute this project. I'll notify you after testing this

**Review by Seniru — CHANGES_REQUESTED** [review]
I tested the game and I foun that you have succesfully fixed the problem. Eventhough there is a problem with your code

See this example, *(The text below is the thing displayed in my terminal)*

```
 ++++++++++++++++++++++++++++++

 Guess letter: a

 b _ _ a k

 ++++++++++++++++++++++++++++++

  You won!
```

image

As you can see, it make a player winner eventhough there are blanks left

**Comment by Seniru** [comment]
After experimenting a little, I found that this problem is due to not adding the initial letters to the played letters list. Adding this at the end of `initGame()` function would fix this problem

```js

/** create new game */
function initGame() {
	word = randWord().split("");
	wordl = word.length;

	for (var i = 0; i < word.length; i++) {
		obfWord.push("_");
	}

    showLetter(word[0]);
    showLetter(word[word.length - 1]);
```
```diff
+    playedLetters.push(word[0]);
+    playedLetters.push(word[word.length - 1]);
}
```

**Comment by Seniru** [comment]
Also can you add `fixes #53 ` to your pull request body

**Review by salif — APPROVED** [review]

**Review by Seniru — APPROVED** [review]
I fixed that problem myself. Your PR is ready to merge!

**Comment by exiam** [comment]
Thanks for your review and corrections (and for the merge). :smiley:

**Comment by Seniru** [comment]
Welcome @exiam 

You can also check out these issues if you are interested :D

- #9 
- #32 
- #11 
- #44

**Pull request merged**
