### PR TITLE
Hangman: Added new words to en-us

### PR DESCRIPTION
**Pull request by moxxiq**

### CODE REVIEW

**Comment by Seniru** [comment]
OMG! About 6500 words. Thanks a lot for the effort!

**Review by salif — APPROVED** [review]

**Review by Seniru — APPROVED** [review]
Congratulations! Your first contribution to this repo is approved!

**Comment by moxxiq** [comment]
Thank you!

**Comment by Seniru** [comment]
Welcome 😊
You can also check these issues if you are interested
- #11 
- #32 
- #44

**Pull request merged**
